version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run: go test ./...
  build_docker:
    docker:
      - image: circleci/docker:18.09
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t bitfield/uptimerobot:test .
      - run: docker push bitfield/uptimerobot:test
workflows:
  version: 2
  dockerbuild:
    jobs:
      - test:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
      - build_docker:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
