version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run: go test ./...
  build_docker:
    machine: true
    steps:
      - checkout
      - run: docker build -t bitfield/uptimerobot:$CIRCLE_TAG -t bitfield/uptimerobot:latest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push bitfield/uptimerobot:$CIRCLE_TAG bitfield/uptimerobot:latest
workflows:
  version: 2
  dockerbuild:
    jobs:
      - test
      - build_docker:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+/
